package jbinvis.frontend.settingspanel;

import jbinvis.frontend.QuickEnable;

public class DigraphSettingsPanel extends javax.swing.JPanel implements QuickEnable{

    /**
     * Creates new form DigraphSettingsPanel
     */
    public DigraphSettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelFileTypeGuess = new javax.swing.JLabel();
        textFileType = new javax.swing.JLabel();

        jLabelFileTypeGuess.setText("File type guess");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(textFileType))
                    .addComponent(jLabelFileTypeGuess))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFileTypeGuess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFileType)
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabelFileTypeGuess;
    private javax.swing.JLabel textFileType;
    // End of variables declaration    
	
    public void setFileTypeText(String text) {
    	textFileType.setText(text);
    }
    
	@Override
	public void enableAll() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void disableAll() {
		// TODO Auto-generated method stub
		
	}

}
